baseurl = "https://gabrielvoelcker.netlify.com/"
languageCode = "en-us"
title = "Gabriel Voelcker"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
theme = "vienna"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "skyvoelcker"
    github = "gvoelcker"
    #gitlab = "Your GitLab username"
    #linkedin = "Your LinkedIn username"
    #googleplus = "Your Google+ user id"
    #facebook = "Your Facebook username"
    #reddit = "Your Reddit username"
    #hackernews = "Your Hacker News username"
    stackoverflow = "8661013"
    #keybase = "Your keybase.io username"
    #instagram = "Your Instagram username"
    # Disqus shortname
    #disqus = "Your disqus shortname"
    # Google Analytics API key.
    #ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    #mixpanel_api_key = "Your Mixpanel API key"
    # author = "Gabriel Voelcker"
    #avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto: gvoelcker@gmail.com)"
    # bio = "Economist from Porto Alegre, Brazil"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "A storage for works, projects and ideas."
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.

