name = "hurock"
description = "A classic sidebar hugo theme"
license = "MIT"
licenselink = "https://github.com/titi/hurock/LICENSE"
homepage = "https://github.com/titi/hurock"
tags = ["blog", "personal"]
features = ["sidebar", "TableOfContents", "highlight", "404"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[author]
  name = "Gabriel Voelcker"
  email = "gvoelcker@gmail.com"
  
  github = "https://github.com/gvoelcker/"
  twitter = "https://twitter.com/skyvoelcker"
  
[permalinks]
posts = "/:year/:month/:filename/"
  
[sidebar]

  github = "https://github.com/gvoelcker/"
  twitter = "https://twitter.com/skyvoelcker"
  