---
title: "Bharath Sunder Sunder 2008"
date: "03/02/2020"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## Paper Analysis 

-   **Research question**: what's the role of the borrower's accounting quality in debt contracting? How does that accounting quality relates to the borrower choosing to go into the public or the private market. 

-   **Intended contribution/importance**: results shed light on how **lender characteristics**(information access and recontracting flexibility) play a role in the manner in which the lenders respond to the quality of information of borrowers.

-   **Hypotheses**: 1a) poorer accounting quality borrowers prefer private debt(banks) over public debt. 1b) Poorer accounting quality borrowers that have greater growth opportunities are more likely to prefer public debt over private debt. 2a) Due to different flexibility, poorer accounting quality borrowers are expected to have more stringent price and non-price contract terms in the case of private debt, whereas only the price terms are affected in the case of public debt. 2b) the impact of accounting quality on price terms for public debt is expected to be greater than that of private debt.

-   **Setting/research design**: sample: 12,676 loans/3,261 firms and 3,681 bonds/ 709 firms. Accounting quality is measured using accrual-based metrics.  

-   **Main results**: poorer accounting quality prefers private debt, unless the firm has private information to be shared that they want others to know(high growth firm). 

-   **Additional results crucial to the story**: banks possess superior information access and processing abilities $\implies$ reduce adverse selection for poorer quality buyers. 

    - Flexibility is a factor when renegotiating contracts.

- **Possible alternative hypotheses**: 

-   **Conclusion**: 

- **Future research**:  

#### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?