---
title: "Bouchaud Kruger Landier Thesmar 2019"
date: "28/03/2020"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## Sticky Expectations and the Profitability Anomaly{.tabset}

### Paper Analysis

-   **Research question**: test whether the profitability anomaly can be directly related to a simple model of sticky expectations in which investors update their beliefs too slowly.  

-   **Intended contribution/importance**: to the behavioral finance literature, that documents both under- and overreaction of analyst forecasts. 

-   **Hypotheses**: 3 cross section predictions: 1) expect analysts to systematically underestimate future profits when current profits are high; 2) expect the profitability anomaly to be stronger for firms that are subject to stickier EPS forecasts; 3) firms with more persistent earnings should be more prone to the profitability anomaly. These 3 predicitions should also hold for profit change (earnings momentum) and past returns(returns momentum).

-   **Model**: investors forecast future profits using a signal and sticky belief dynamics. 

- **Setting/data**: using analyst forecast data, the paper measures expectation stickiness at the firm level. Test model predictions by using EPS forecast by financial analysts on IBES.

-   **Main results**: past profits forecast future returns(*profitability anomaly*)(?). 1) analysts on average are too pessimistic regarding the future profits of high-profit firms; 2) the profitability anomaly is stronger for stocks that are followed by stickier analysts; 3) the profitability anomaly is stronger for stocks with more persistent profits. 

-   **Additional results crucial to the story**: cross-sectional results: 

- **Possible alternative hypotheses**: 

-   **Conclusion**: 

- **Future research**:  

### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?

### Summary
