---
title: ""
date: "24/02/2020"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
# [**Dichev Skinner 2002**](https://onlinelibrary.wiley.com/doi/abs/10.1111/1475-679X.00083)

## {.tabset}

### Paper Analysis

-   **Research question**: do managers' choices reduce the likelihood their firms will violate accounting-based debt covenants?

-   **Intended contribution/importance**: contributes to the debt covenant literature with an new sample that directly observes private loans and measure the closeness to debt covenants in private debt agreements.

-   **Hypotheses**: do accounting managers make accounting choices that reduce likelihood of violating debt covenants? 

-   **Setting/research design**: Dealscan uses private loans data(30,000 obs) to construct precise measures of closeness to debt covenants in private debt agreements. 

-   **Main results**: clear support for debt covenant hypothesis: unusually small number of firm/quarters with financial measures just below covenant thresholds and an unusually large firms that just meet/beat thresholds. Private lenders set debt covenants tightly and use them as "trip wires"?????? for borrowers, that technical violations occur relatively often and violations are not necessarily associated with financial distress.

-   **Additional results crucial to the story**: the relative tightness of covenant restrictions and corresponding frequency of violations is inconsistent with lenders imposing serious consequences on borrowing firms. Leverage is a noisy proxy for tightness. Before the 1st violation, managers try even more actively to avoid violations. It is not common for the borrower to face serious consequences.

- **Possible alternative hypotheses**: ex-ante contracting has lenders systematically placing covenant thresholds slightly below actual values? What is the form of management that leads to this result? Is it through real results or is there manipulation(assuming the goal is clear)?

- **Conclusion**: managers actively avoid debt covenant violations.

- **Future research**: how are the terms of debt covenants determined as a function of firm characteristics? Extend to other covenants?

### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?

### Summary

The paper sets out to test **whether managers actively try to avoid debt covenant violations**(the debt covenant hypothesis). It innovates in using Dealscan, which has a 30,000 sample of private loans that has **precise** measures of closeness to debt covenants in private debt agreements. It is reported that a unusually high number of observations just meat/beat the threshold, which indicates manipulation by the managers. 

**Tests**: 1) how much slack (realization - threshold) firms have? 2) do firms just meet/beat the threshold to avoid DC violation? Even more if it is a 1st-time violation? Perform same analyses in subsample by type of debt covenant; $\rightarrow$ validates the debt covenant hypothesis;  3) robustness checks for 2): randomize under smooth assumption; 4) compares violation and non-violation firms: violations are frequent and not as serious as previously thought; 


- Six possible lender responses to violations:

1) termination of the lending agreement;

2) demand for immediate repayment;

3) increased collateral;

4) increased interest rate; 

5) imposition of additional covenant constraints; 

6) waiver of the violation;

- If managers are aware of the thresholds that when violated would lead to a debt covenant violation $\implies$ they obviously will try to avoid its violation (debt covenant hypothesis ✅ ). What are the means they use to achieve this? (who plays dirty in the short term gets worse return in the long term?)(read last bit of 1097: financial situation gets to a point it's not worth to manage reported numbers)

- If in the violation year there is no manipulation $\implies$ 


