---
title: "Fischer Verrecchia (2000)"
date: "30/03/2020"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## Reporting Bias{.tabset}

### Paper Analysis

-   **Research question**: presenting a model of managerial reporting bias for a setting in which the capital market is uncertain about the manager's reporting objective. 

-   **Intended contribution/importance**: the model yields insights into factors that affect the slope and intercept terms in a regression of price on earnings. Unobservable bias(i.e. earnings manipulation) reduces the usefulness of reports of firm performance: the paper delves into the bias arising from the measurer's application of the measurement method. 

-   **Key assumption**: relaxes the assumption that the market perfectly knows the manager's reporting objective.

-  **Model**: the manager's reporting bias reduces the value relevance of the manager's report: it **adds noise** to the report. 

-   **Main results**: The information content of the manager's report, as captured by the earnings slope coefficient, falls as the private cost to the manager of biasing report falls, and as the uncertainty about the manager's objective increases. The magnitude of the adjustment for the expected amount of bias falls as uncertainty about the manager's objective increases. 

-   **Additional results crucial to the story**: *ex-ante* benefit from biasing the report is positive if there is sufficient uncertainty about the manager's reporting objective. 

- **Possible alternative hypotheses**: 

-   **Conclusion**: bias in the manager's report reduces the value relevance or the information content of the report. Managers would lobby to maintain reporting discretion.

- **Future research**:  

### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?

### Summary

Brief model description(can link this to Ferri et al 2018): 

- The firm yields a terminal value of $\tilde{v}$, where the manager's and the market's priors for $\tilde{v}$ are normally distributed with mean 0 and variance $\sigma_v^2$. 






