---
title: "Jensen & Meckling (1976)"
date: "10/02/2019"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## Paper Analysis 

-   **Research question**: how does the conflict of interest between managers and stockholders take place? And between stockholders and debtholders?

-   **Intended contribution/importance**: develop a theory of the ownership structure of the firm. Define the concept of *agency costs*. 

-   **Hypotheses**: 

-   **Main results**: what the theory helps to explain:

    1) why managers in a firm with mixed financial structure will choose a set of activities for the firm such that the total value of the firm is less had it had a sole owner, independent of the type of market it operates in.
    
    2) why the failure to maximize the value of the firm is consistent with efficiency.
    
    3) why selling common stock is a viable source of capital even thouh managers don't literally maximize the value of the firm. 
    
    4) why debt was used even before it offered any tax advantage relative to equity.
    
    5) why preferred stock should be issued.
    
    6) why accounting reports would be provided voluntarily to creditors and stockholders; why independent auditors would be engaged by management to testify to the accuracy and correctness of such reports.
    
    **7) why lenders often place restrictions on the activities of firms to whom they lend, and why firms would themselves be led to suggest the imposition of such restrictions** - **What about the cost of capital? How is it related to this?**. Firms suggest this imposition of restrictions to limit divergences of interest, but would never suggest something that it's not of their interest. 
    
    8) why some industries are characterized by owner-operated firms whose sole outside source of capital is borrowing. 
    
    9) why highly regulated industries will have higher debt equity ratios for equivalent levels of risk than the average non-regulated firm.
    
    10) Why security analysis can be socially productive even it does not increase portfolio returns to investors.

-   **Additional results crucial to the story**: 

Regarding **Managers vs Stockholders:**

  a) Finding that agency costs are non-zero (i.e., $\exists$ costs associated with the separation of ownership and control in the corporation) $\implies$ that the agency relationship is non-optimal. The *existence and size of agency costs depends on the nature of the monitoring costs, the tastes of managers for non-pecuniary benefits and the supply of potential managers who are capable of financing the entire venture out of their personal wealth*.

  b) As the owner-manager's fraction of equity falls $\implies$ he will be encouraged to expend resources in perquisites.

  c) the owner will bear the monitoring costs for as long as the welfare increment offsets the costs.
  
  d) If we are looking at a non-optimal relation, why so many people hand their money to corporations? - Limited liability. - Irrelevance of capital structure: agency costs provide stronger reasons for arguing that the distribution of future cash flows is not independent of the capital or ownership structure.  

Regarding **Stockholders vs Debtholders:**

  a) Why wouldn't a owner put up little capital and simply borrow the rest? 1) incentive effects associated with highly leveraged firms. 2) Monitoring costs these incentive effects engender. 3) Bankruptcy costs. 
  
  b) 4.2: monitoring costs prevent the loss of value of bonds. The managers want these costs to be as low as possible. 
  
  c) If bankruptcy probability increases $\implies$ operating costs and revenues are diversely affected.  Ex: higher bankruptcy $\rightarrow$ higher salary to top executives to induce them to accept the role.
  
  d) **Agency costs associated with debt**:
  
  1) opportunity wealth loss caused by the impact of debt on the investment decisions of the firm;

  2) monitoring and bonding expenditures by the bondholders and owner-manager may force firm to non-optimal decisions;
  
  3) bankruptcy and reorganization costs.
  
  e) Why use debt given its agency costs? 1) tax subsidy on interest payments; 2) financial limitation to exploit profitable opportunities (opportunity loss).
  
Regarding the **Corporate Ownership Structure Theory**:

  - What is the optimal ratio of outside equity to debt? The one that minimizes agency costs. 

- **Possible alternative hypotheses**: 

-   **Conclusion**: agency costs are real but the corporation still survived against other alternatives. 

- **Future research and Issues**:  

    1) Yes it is possible for managers to obtain a funding much bigger than the amount he invested in firms, right? It depends on the covenants they impose. Nobody is going to invest 100,000,000 so 20's get to fly on private planes. The money works as a fuel to reach the objectives, assuming the contract aligns their interests. 

    2) The paper does not deal with repeated games. That is, what about the reputation of managers? Just as bankruptcy can negatively impact operating costs and revenues, can't the behavior of manager impact the perception of outsiders of the firm? How are these costs classified? Can you dissociate firm culture from manager's culture? Is this behavior different if the manager is the founder(assume founders are more emotionally invested in the firm)?
    
    3) What if outsiders can vote? How much can the board of directors/trustee mitigate the conflict?
    
    4) What about personal info about the managerS? Owners, founders, heirs...

### When evaluating a paper:

- **Does the study address an important question?** 

Yes. Agency costs and conflicts of interest are ever present in analyzing firms,

- **Does the study extend prior literature?**

Yes in the sense of coming up with a theory that encapsulates and formalizes the relationship between managers vs stockholders; stockholders vs debtholders. 

- **Is the study's conceptual framework logically consistent and credible?**

- **Are the sample, proxies, and empirical models appropriate?**

It's a theory paper.

- **Does the study consider and rule out alternative explanations?**







