---
title: "Mullner Simon 2020"
date: "07/04/2020"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## On the Optimality of Imperfect Monitoring{.tabset}

### Paper Analysis

-   **Research question**: builds a model that shows that a commitment to **restricted monitoring** can lead to significant benefits for the Board.  

-   **Intended contribution/importance**: 

-   **Hypotheses**: 

- **Assumptions**: the Board and Shareholders have aligned interests. The Manager has empire building preferences. 

-   **Setting/research design**: 

-   **Main results**: monitoring is not always beneficial.

-   **Additional results crucial to the story**:

- **Possible alternative hypotheses**: 

-   **Conclusion**: 

- **Future research**: analyze Board's dependency problem through different utility levels. A more independent Board (concerned with reputation) might adopt a higher target posterior belief? A more dependent Board has stronger incentives to do *ex post* monitoring. 

### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?

### Summary
