---
output: html_document
---
## **Paper Checklist** {.tabset}

### Does the study address an important problem?

#### **Does the study address an important problem?**

### Does the study extend prior literature?

#### **Does the study extend prior literature?**

### Is the study's conceptual framework logically consistent and credible?

#### **Is the study's conceptual framework logically consistent and credible?**

### Are the sample/proxies/empirical models appropriate?

#### **Are the sample/proxies/empirical models appropriate?**

### Does the study consider and rule out alternative explanations?

#### **Does the study consider and rule out alternative explanations?**

### Presenting the paper

#### **What to address when presenting**

-   Research question

-   Intended contribution/importance

-   Hypotheses

-   Setting/research design

-   Main results

-   Additional results crucial to the story

    - Deal with possible alternative hypotheses

-   Conclusion

### What question is every method trying to address?

#### **What question is every method trying to address?**

#### **Libby Box**
