---
title: "Smith and Warner (1979)"
date: "10/02/2020"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## Paper Analysis 

-   **Research question**: how are debt contracts written to control the conflict between bondholders and stockholders?

- **Additional Questions**: is the total value of the firm influenced by how the conflict is dealt with? *Irrelevance Hypothesis* vs *Costs of Capital Hypothesis*. 

- **Irrelevance Hypothesis**: a) under a *fixed investment policy*: covenants only alter the distribution of the payoffs to the claimholders, that are fixed in total value. b) under a *not fixed investment policy*: the influence of external markets or the possibility of restructuring the firm's claims implies that the choice of financial contracts is irrelevant to the value of the firm.

- **Costs of Capital Hypothesis**: the control of the bondh vs stockh conflict can increase the value of the firm. Covenants can lower the monitoring costs. This hypothesis presupposes that there are benefits associated with the inclusion of risky debt, otherwise it would never be issued. 

-   **Intended contribution/importance**: analyze types of covenants

-   **Hypotheses**: stockholders take actions to maximize the value of their equity, not necessarily of maximizing the value of the firm and its bonds. 

-   **Setting/research design**:

-   **Main results**:  

-   **Additional results crucial to the story**: conflicts rise in 4 principal ways:

    1) Dividend payment: bonds lose value when firm raises the dividend payment.
    
    2) Claim dilution: bonds lose value when firm issues new bonds.
    
    3) Asset substitution: if a firm sells bonds with the purpose of engaging in low variance projects and the bonds are valued at prices commensurate with that low risk, the value of the stockholders' equity rises and the value of the bondholders' claim is reduced by substituting projects which increase the firm's variance rate.
    
    4) Underinvestment: a firm rejects positive NPV projects when the their benefits go to the debtholders.
    
Given that covenants have existed for so long, it is assumed that they must be relevant. Covenants are costly, which lead to rejecting the Irrelevance Hypothesis.

If covenants are very expensive for the firms to enforce, then firms wouldn't want to offer them in the first place. So what are the costs of covenants?

    1) Legal liabilities of the bondholders: assigning legal liability to bondholders represent a real cost to the firm's owners because of the legal costs involved in the determination of bondholder liability.
    
    2) Trustees: when the debt is held by lots of bondholders, the firm can offer a contract that appoints a trustee to help assure that the optimal amount of covenant enforcement will take place. What about repeated moves, how does the reputation of the trustee comes into play? Bribing..
    
    3) Trustee Negligency: apart from being a costly contract, the trustee can also, in good faith, be negligent of his responsibilities.
    
    4) Public vs private debt: private is exempt of registration. These can lead to a huge benefit to the firm. Except when the firm has proprietary information that it doesn't want to share to a particular, well-informed, lender. 
    
    5) What happens when you **violate**? Default! Renegotiation(do you have to renegotiate with one entity or thousands? How much flexibility do you have?)! Bankruptcy.

- **Possible alternative hypotheses**: Irrelevance Hypothesis: rejected. 

- **Conclusion**: covenants are costly: therefore they must increase the firm value for the benefit of bondholders. Why stockholders issue debt?

- **Future research**:  

    - What are all the pressures a stockholder can receive? Apart from debtholders, managers, employees, government(?)? How can they affect the way they deal with debtholders?

    - When thinking about how to deal with bondholders, what other factors must take into consideration? For ex: say stockholders are forbidden from issuing more debt given a current debt covenant, what if the managers want more funding to meet the company's goal for that year?
    
    - If you dissociate managers completely from being stockholders, can we expect companies to behave differently? 

#### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?