---
title: "Sweeney (1994)"
date: "03/02/2019"
html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    fig_caption: true
---
## Paper Analysis 

paper deals with accounting changes, costs of default and accounting-based covenants violated by 130 firms reporting violations in annual reports. 

timeline: why firms default? -> how do managers behave? -> why do they use income increasing measures? 1) to lower the probability of technical violation; 2) offset declines in liquidity?

- **Research question**: how do managers behave around the time in which firms violate constraints?

- **Intended contribution/importance**: provides direct evidence in support of the covenant-based hypothesis that managers of firms approaching technical default respond with income-increasing accounting changes. Extends the literature by providing evidence that managers accountings responses depend on whether default costs are imposed by creditors, whether managers have accounting flexibility and whether significant tax costs are associated with the available accounting changes. Test the proposition that managers change accounting procedures in response to tightening debt-covenant constraints. 1) Different than Healy and Palepu(1990): they examine firms that violate minimum net worth and working capital rather than dividend constraints, which could be potentially more powerful tests of the covenant-based hypothesis. It also analyzes accounting changes rather than abnormal accruals. 2) documents whether accounting changes actually delay violation of accounting-based restrictions for one or more accounting periods. 3) provides evidence that managers' accounting responses depend on whether default costs are imposed by creditors, whether managers have accounting flexibility, and whether significant tax costs are associated with the available accounting changes. 

- **Hypotheses**: how do managers behave around the time that firms violate accounting-based restrictions found in debt agreements? Managers' accounting responses depend on whether default costs are imposed by creditors and whether managers have accounting flexibility available. 

- **Setting/research design**: the paper identifies points in time wen firms violate accounting-based restrictions in their debt agreements and document the time series of managers' choices around these violations. Firms' able to exercise accounting flexibility to circumvent constraints and avoid violation are excluded. 

examine the time series of managers' accounting choices prior to firms violating accounting-based restrictions in debt agreements. The paper documents whether managers change accounting procedures, which types of accounting procedures managers change, when managers make these changes and to what extent these changes affect the restrictiveness of accounting-based covenants. Analyzes accounting changes *rather* than abnormal accruals and by examining firms that violate minimum net worth and working capital covenants rather than dividend constraints. 

- **Main results**: managers of default firms make a greater number of income-increasing accounting changes relative to managers of similar firms. Also, the paper fails to provide conclusive evidence that managers of default firms make income-increasing accounting changes to offset tightening debt-covenant constraints. 

- **Additional results crucial to the story**: private lending agreements are the first ones to be violated; net worth and working capital are the most frequently violated restrictions; 52% of the cases the lenders require concessions from borrowers to resolve default; the accounting changes are able to delay technical default in 5/22 cases. Managers of firms having accounting flexibility and bearing default costs are more likely to make income-increasing accounting changes in response to tightening debt-covenant constraints than managers of firms not having accounting flexibility and/or not bearing default costs.

- **Possible alternative hypotheses/limitations**: absence of an ideal control group -> one that differs only with respect to closeness to covenants; *interpretations*: a) managers make accounting changes to offset increases in the tightness of accounting-based restrictions as their firms approach technical default; b) managers of default firms switch to most efficient set of accounting choices for their financially distressed firms; 

- **Conclusion**: this paper provides direct evidence in support of the covenant-based hypothesis that managers of firms approaching technical default respond with income-increasing accounting changes. It also externds the literature by providing evidence that managers' accounting responses depend on whether default costs are imposed by creditors, whether managers have accounting flexibility and whether significant tax costs are associated with the available accounting changes. 

- **Future research**:  

#### When evaluating a paper:

- Does the study address an important question?

- Does the study extend prior literature?

- Is the study's conceptual framework logically consistent and credible?

- Are the sample, proxies, and empirical models appropriate?

- Does the study consider and rule out alternative explanations?