---
title: 'Benford''s Law: Using R'
author: Gabriel Voelcker
date: '2018-08-10'
slug: benford-s-law-using-r
categories: []
tags:
  - r
  - benford
  - distribution
Description: ''
Tags: []
---
I am thinking of a number from 1 to 99. I am giving you 2 seconds to guess which is the first **digit** of that number. 

1.

2.

So, which number did you think of? Actually, that's irrelevant. My intention here is to make you reflect about this question: what were the odds of you correctly guessing the first digit? 

First of, there are 9 possibilities(0,1,2,3,4,5,6,7,8,9) since 0 is never a first digit among the possibilities I've described. So, if you chose 4, there were 11/99 = 1/9 =~ 11% of chances that you guessed correctly, right? So far, simple math. This is illustrated by the figure below. 

INCLUDE 1/9 DISTRIBUTION HERE

But let me ask you now about a different set of numbers: 2^n^.  Suppose, the first digit of all the powers of 2 from 1 to 1000. (2, 4, 8, 16, 32...). Would you say that by choosing 4 the odds of guessing correctly would remain 1/9? 
The answer is no! But the issue here is why? What drives that? Thanks to two gentlemen, Simon Newcomb and Frank Benford, we have something to say about that. In [**1881**](http://gerry.lamost.org/upload/newcomb.pdf), Simon Newcomb noticed that the first pages of a logarithm book were usually more worned out than the later ones. From this, he derived his intuition that given a list of arbitrary numbers more numbers will tend to begin with an "1" than any other digit. 

But it wasn't until [**1938**](https://www.jstor.org/stable/984802?seq=1#page_scan_tab_contents) that Frank Benford formalized this discovery, which is now called Benford's Law. 







