---
title: About the author
author: Gabriel Voelcker
date: '2018-08-02'
slug: about-the-author
categories: []
tags: []
Description: ''
Tags: []
---

I am an economist from Brazil. My alma mater is [**Universidade Federal do Rio Grande do Sul**](https://www.ufrgs.br/fce/), and I graduated in 2016. I am currently finishing my masters in Accounting in [**Universidade do Vale do Rio dos Sinos**](http://www.unisinos.br/mestrado-e-doutorado/ciencias-contabeis/presencial/porto-alegre). My main research interests include: econometrics, microeconomics, game theory, risk, behavioural economics, decision-making, cultural economics and dividend policy. 

You can find everything I have published in my [**Google Scholar**](https://scholar.google.com.br/citations?user=WP7S4-gAAAAJ&hl=pt-BR&oi=sra) page. I also have  worked as a research assistant in three distinct research projects: [**1**](https://onlinelibrary.wiley.com/doi/abs/10.1111/1475-679X.12201), a second one which hasn't been published yet and [**3**](https://www.lume.ufrgs.br/bitstream/handle/10183/153772/Poster_45933.pdf?sequence=2).

My previous work experiences include working at [**Coca-Cola Brazil**](https://www.cocacolabrasil.com.br/), [**XP Investimentos**](https://www.xpi.com.br/) and [**Auxiliadora Predial**](https://www.auxiliadorapredial.com.br/). 

Regarding my academic approach, I leave you with my favourite quote:

*"I consider that a man's brain originally is like a little empty attic, and you have to stock it with such furniture as you choose. A fool takes in all the lumber of every sort that he comes across, so that the knowledge which might be useful to him gets crowded out, or at best is jumbled up with a lot of other things, so that he has a difficulty in laying his hands upon it. Now the skillful workman is very careful indeed as to what he takes into his brain-attic. He will have nothing but the tools which may help him in doing his work, but of these he has a large assortment, and all in the most perfect order. It is a mistake to think that that little room has elastic walls and can distend to any extent. Depend upon it there comes a time when for every addition of knowledge you forget something that you knew before. It is of the highest importance, therefore, not to have useless facts elbowing out the useful ones?"*

(A Study in Scarlet, by Arthur Conan Doyle.)