---
output: html_document
---

# 14.121 - Microeconomic Theory I{.tabset}


## **1) Utility and Revealed Preferences**

The first class of the semester covers basic Microeconomic topics such as Utility Theory and Revealed preferences. We use an axiomatic approach to the utility theory to find less obvious asumptions of utility theory. It was recognized that utility could not be measured or observed directly, so instead economists devised a way to infer underlying relative utilities from observed choice. 

### Utility Theory

#### [**Utility Theory**](https://en.wikipedia.org/wiki/Utility): 

In Economics, the concept of **utility** is used to model worth/value. In most economic models, agents are assumed to have a utility function that they maximize. The utility function approach usually serves two purposes:

1) Model for predicting behavior (positive); i.e. agent will maximize utility.
    
2) Framework for welfare analysis (normative); i.e. utility is "good".

If we reflect about this utility approach, we have an opportunity to introduce one useful economic methodology: the **axiomatic approach**.
    
#### [**Axiomatic Approach**](https://en.wikipedia.org/wiki/Axiomatic_system): 

The idea is to *find simple axioms which together are equivalent to
less obvious assumptions of utility theory*.  Any set of axioms from which some or all axioms can be used in conjunction to logically derive theorems exemplify an axiomatic approach. A theory consists of an axiomatic system and all its derived theorems. An axiomatic system that is completely described is a special kind of formal system. A formal theory typically means an axiomatic system, for example formulated within model theory. A formal proof is a complete rendition of a mathematical proof within a formal system.

#### [**Utility Function**](https://en.wikipedia.org/wiki/Utility#Utility_function):

A utility function represents a consumer's preference ordering over a choice set.  Consider a set of alternatives facing an individual, and over which the individual has a preference ordering. A **utility function** is able to represent those preferences if it is *possible to assign a real number to each alternative*, in such a way that alternative a is assigned a number greater than alternative b if, and only if, the individual prefers alternative a to alternative b. In this situation an individual that selects the most preferred alternative available is necessarily also selecting the alternative that maximises the associated utility function. In general economic terms, a utility function measures preferences concerning a set of goods and services. Often, utility is correlated with words such as happiness, satisfaction, and welfare, and these are hard to measure mathematically. Thus, economists utilize consumption baskets of preferences in order to measure these abstract, non quantifiable ideas. 

Gérard Debreu precisely defined the conditions required for a preference ordering to be representable by a utility function. For a finite set of alternatives these require only that the preference ordering is complete (so the individual is able to determine which of any two alternatives is preferred, or that they are equally preferred), and that the preference order is transitive.

##### **Utility Function Definition**: 
A **utility function** u defined on X is a real-valued function u: X -> $\mathbb{R}$. A more foundational place to start to think about assumptions inherent in utility theory is treating preferences as a primitive.

##### **Preference Definition**: 

*P* is a subset of X x X, where we write x $\succeq_P$ *y* if (x,y) $\in$ *P*. Interpretation of x $\succeq_P$ y: agent thinks "*x* is **at least as good as** *y*".

So the utility function *u*: X -> $\mathbb{R}$ **represents** the preference P if:

  u(x) ≥ u(y) $\iff$ x $\succeq_P$ y.

Note: many different utility functions can represent the same set of
preferences. e.g., if X = {x, y, z}, and P = {(x, y),(x, z),(y, z)}
(i.e x $\succeq_P$ y, x $\succeq_P$ z, y $\succeq_P$ z).

In general if u represents P, then so does *f* $\circ$ *u*, for any *strictly* increasing function *f*.

##### **Properties of Preferences**:

- The preference relation $\succeq_P$ is **complete** on *X* if $\forall$*x*, *y* $\in$ *X*, either *x* $\succeq_P$ *y* or *y* $\succeq_P$ *x*.

- The preference relation $\succeq_P$ is **reflexive** on *X* if $\forall$*x* $\in$ *X*, *x* $\succeq_P$ *x*.

- The preference relation $\succeq_P$ is **transitive** on *X* if *x* $\succeq_P$ *y* and *y* $\succeq_P$ *z* $\implies$ *x* $\succeq_P$ *z*.

Our first result is the following **proposition**: if $\succeq_P$ is represented by *u* on *X*, then $\succeq_P$ is complete, reflexive and transitive.

**Proof**:

- Complete: given any *x,y* $\in$ *X*, either u(x) ≥ u(y) or u(y) ≥ u(x) (property of real numbers). This implies x $\succeq_P$ y or y $\succeq_P$ x(by representation assumption).

- Reflexive: given any x $\in$ X, u(x) ≥ u(x) $\implies$ x $\succeq_P$ x.

- Transitive: if x $\succeq_P$ y and y $\succeq_P$ z, then u(x) ≥ u(y) and u(y) ≥ u(z). Transitivity of ≥ on $\mathbb{R}$ implies that u(x) ≥ u(z) $\implies$ x $\succeq_P$ z.

Usually we leave out preferences that do not satisfy these 3 assumptions. Now let's consider the other way around: if $\succeq_P$ is complete, reflexive and transitive, then can it be described by some utility function? It depends on whether the X is **finite**. 

Some comments:

1) With finite sets, apparently assuming utility maximization is exactly the same as assuming preferences are complete, reflexive and transitive.

2) Any critique of utility theory is a critique of one of these assumptions (or our notion of preferences). If we are happy with these, then we are happy with utility functions.

3) To turn preferences into *predictive* or *welfare tool*, we need to explicitly state that people will do what they prefer.

##### [**Criticisms of Utility Theory**](https://en.wikipedia.org/wiki/Utility#Discussion_and_criticism):

Some main criticisms of the UT:

1) **Realism**: people don't really act *as-if* they maximize utility, which is not necessarily true: no one chooses objects after consulting some numerical index of goodness. So, what can we **falsify**?

2) **Inconsistent or probabilistic choice**: the individual may choose an object with lower utility for some random reason. But the standard model assumes choices are innate and unchanging. This is the notion of [**random utility**](https://www.sciencedirect.com/topics/social-sciences/random-utility-theory).

3) **Origin of preferences**: tastes change, or [**De Gustibus Non Est Disputandum**](https://www.jstor.org/stable/1807222?seq=1#page_scan_tab_contents).

4) **Procedural vs consequentialist aspects of choice**: If x is chosen from set A, individual is just as well off if given a choice from A vs simply given x without opportunity to choose. But maybe individuals value the freedom to choose, while at the same time too many options can be bad(choice overload).

Despite the criticism, the standard model still remains the workhorse model and remains useful, but important to remember it is **based on assumptions on human behavior** and not laws of nature.

#### Not clear how the content before here is bridged to the next part

**Monotone Definition**: the preference relation $\succeq$ on X is **monotone** if x $\in$ X and y ≥ x implies y $\succeq$ x. If y ≠ x and y ≥ x, then **strictly monotone**. ("goods are goods"???)

[**Locally non-satiated definition**](https://en.wikipedia.org/wiki/Local_nonsatiation): states that for any bundle of goods there is always another bundle of goods arbitrarily close that is preferred to it. Formally, if $\forall$x $\in$ X and all $\delta$ > 0, $\exists$y s.t. ||y - x|| < $\delta$ and y $\succeq$ x. 

Some things to note:

1) Local nonsatiation is implied by **monotonicity of preferences**. Because the converse isn't true, local nonsatiation is a weaker condition.

2) There is no requirement that the preferred bundle y contain more of any good – hence, some goods can be "bads" and preferences can be non-monotone.

3) It rules out the extreme case where all goods are "bads", since the point x = 0 would then be a bliss point.

4) Local nonsatiation can only occur either if the consumption set is unbounded (open) (in other words, it cannot be compact) or if x is on a section of a bounded consumption set sufficiently far away from the ends. Near the ends of a bounded set, there would necessarily be a bliss point where local nonsatiation does not hold.

[**Convex preferences definition**](https://en.wikipedia.org/wiki/Convex_preferences): are an individual's ordering of various outcomes, typically with regard to the amounts of various goods consumed, with the property that, roughly speaking, "averages are better than the extremes". The concept roughly corresponds to the concept of diminishing marginal utility without requiring utility functions. Formally, the preference relation $\succeq$ on X is **convex** if $\forall$x, y $\succeq$ x, z $\succeq$ x and y ≠ z implies that for all $\alpha$ $\in$ (0,1): $\alpha$y + (1 - $\alpha$)z $\succeq$ x. This leads to "moderation in all things".

[**Continuous preference definition**](https://en.wikipedia.org/wiki/Preference_(economics)#Meaning_in_decision_sciences): Continuity simply means that there are **no ‘jumps’** in people's preferences. In mathematical terms, if we prefer point A along a preference curve to point B, points very close to A will also be preferred to B. This allows preference curves to be differentiated. The continuity assumption is "stronger than needed" in the sense that it indeed guarantees the existence of a continuous utility function representation and it is useful because **it does not require the set of preferences to be finite**. Continuity is, therefore, a sufficient condition, but not a necessary one, for a system of preferences. Formally, the preference relation $\succeq$ on X is **continuous** if it is preserved under limits: for any sequence{($x^n,y^n$)}$_{n=1}^{\infty}$ with $x^n$ $\succeq$ $y^n$ for all *n*, x $\succeq$ y, where x and y are limit points of the sequence, respectively.

**The continuity assumption is assumed in order to extend the earlier representation theorem to commodity space X which is not countable.** For continuity proof, see [**here**](https://gabrielvoelcker.netlify.com/mit/debreu_continuityproof.pdf).

[**Debreu's Theorem**](https://en.wikipedia.org/wiki/Debreu_theorems): the Debreu theorems come to answer the following basic question: what conditions on the preference relation of the agent guarantee that such representative utility function can be found? So, his 1954 theorems state that for every preference relation which is complete, transitive and continuous, this relation can be represented by a [**continuous ordinal utility function**](https://en.wikipedia.org/wiki/Ordinal_utility#Continuity). **Slide definition**: supposte the rational preference relation is $\succeq$ on X is continuous. Then there is a continuous utility function u(x) that represents $\succeq$. See p 47 of [**MWG**](https://gabrielvoelcker.netlify.com/mit/Mas-Colell,%20Whinston%20&%20Green%20-%20Microeconomic%20Theory.pdf).

**Choices as primitive**: So far we have taken preferences as a primitive.
Another approach is to take treat choice behavior as the primitive. Let $\mathcal{B}$ be a set of nonempty subsets of X and Ch($\circle$) be a choice rule that assigns a nonempty set of chosen elements Ch(B) $\subset$ B for each B $\in$ $\mathcal{B}$. A lot of modern literature begins this way, more [**here**](https://www.taylorfrancis.com/books/9780429498619).

#### **Recap**

1) Axiomatic method is a useful way to think about complex
assumptions we make.

2) With finite choice sets, the assumption of a utility representation is equivalent requiring preferences to be complete, reflexive, and transitive. Continuity yields utility representation when choice set not finite.

### **Revealed Preferences**

- [**Revealed Preferences Theory**](https://en.wikipedia.org/wiki/Revealed_preference):  is a method of analyzing choices made by individuals, mostly used for comparing the influence of policies on consumer behavior. Revealed preference models assume that the preferences of consumers can be revealed by their purchasing habits.

In terms of choice experiment, suppose a consumer is repeatedly asked to choose a consumption bundle x $\in$ $\mathbb{R}^{L+}$. The consumer r is confronted with different prices and we observe resulting choices C = {($p^1,x^1$),($p^2,x^2$),...}. What can we say about preferences and what axioms they satisfy? Need some **structure on preferences**, otherwise indifference could rationalize any behavior.

So, we turn back to the **local nonsatiation condition**: the utility function u: X -> $\mathbb{R}$ satisfies local nonsatiation if $\forall$x $\in$ X, and all $\varepsilon$ > 0, $\exists$y $\in$ X with || y - x || < $\varepsilon$ such that u(y) > u(x). Observe: x,y at price p and p$\circ$x ≥ p$\circ$y. If x chosen when y could have been chosen, x is **directly revealed preferred** to y. The notation for this is **$xR^Dy$**. 

If there is a sequence of preferences such as: $xR^Dz_1$, $z_1R^Dz_2$, ..., $z_nR^Dy$, we can say that x is (indirectly) **revealed preferred** to y and write xRy. Denote strict counterparts with $P^D$ and P, respectively: $xP^Dy$ $\iff$ p$\circ$x > p$\circ$y.

**General Axiom of Revealed Preferences(GARP)**: a set of consumption choices {($p^1,x^1$),($p^2,x^2$),...,($p^n,x^n$)} satisfies the general axiom of revealed preferences if and only if:

$x^iRx^j$ $\implies$ $p^j\circ x^j$ ≤ $p^i\circ x^i$, $\forall i,j$. 

If $x^i$ is revealed preferred to $x^j$, then $x^i$ is only weakly affordable at $x^j$'s prices.

Put differently: if $x^i$ is indirectly revealed preferred to $x^j$, then $x^j$ cannot be strictly directly revealed preferred to $x^i$. That is,

$x^iRx^j$ $\implies$ not $x^jP^Dx^i$

Some textbooks have other axioms of revealed preferences. 

1) [**The Weak Axiom of Revealed Preference(WARP)**](https://en.wikipedia.org/wiki/Revealed_preference#The_Weak_Axiom_of_Revealed_Preference_(WARP)): is one of the criteria which needs to be satisfied in order to make sure that the consumer is consistent with his preferences. If a bundle of goods a is chosen over another bundle b when both are affordable, then the consumer reveals that they prefer a over b. WARP says that when preferences remain the same, there are no circumstances (budget set) where the consumer strictly prefers b over a. By choosing a over b when both bundles are affordable, the consumer reveals that their preferences are such that they will never choose b over a, while prices remain constant. Put simply: if $x^iR^Dx^j$ and $x^i$ ≠ $x^j$, then it is not the case that $x^jR^Dx^i$.

2) [**The Strong Axiom of Revealed Preference(WARP)**](https://en.wikipedia.org/wiki/Revealed_preference#Completeness:_The_Strong_Axiom_of_Revealed_Preferences_(SARP)): The strong axiom of revealed preferences is equivalent to the weak axiom of revealed preferences, except that the consumer is not allowed to be indifferent between the two bundles that are compared. That is, if WARP concludes a $\succeq$ b, SARP goes further and concludes that a $\succ$ b. Put simply: if $x^iRx^j$ and $x^i$ ≠ $x^j$, then it is not the case that $x^jRx^i$.

**Afriat's Proposition**: the central result of consumer theory is Let {($p^1,x^1$),...,($p^n,x^n$)} be a finite set of consumption choices. If a finite set of demand data violates GARP, then these data are inconsistent with choice according to locally nonsatiated, complete, and transitive preferences. Conversely, if a finite set of demand data satisfies GARP, then these data are consistent with choice according to strictly increasing, continuous, convex, complete and transitive preferences.

[**Kreps**](https://gabrielvoelcker.netlify.com/mit/David%20M.%20Kreps-Microeconomic%20Foundations%20I_%20Choice%20and%20Competitive%20Markets-Princeton%20University%20Press%20(2013).pdf): shows the equivalence of GARP and the existence of a solution to a set of linear inequalities. From this  solution, we can construct a utility function rationalizing the choices of the consumer. Chapter 4 of Kreps for complete proof.

- Kreps and Varian emphasize that with finite data on (p, x), strictly increasing or continuous or convex adds no testable restrictions (if satisfy GARP, can construct a utility function satisfying these extra conditions)

GARP is discussed in fields where people are interested in whether some utility function can explain things. Examples: 1) Behavioral: can we explain altruism etc. with utility?; 2) Family/household: are interfamily dynamics causing inefficiency or do families act like they have some common goal?

Then the slides turn to some examples of choices:

1) [**Giving According to GARP: An Experimental Test of the Consistency of Preferences for Altruism**](https://www.jstor.org/stable/2692289?seq=1#page_scan_tab_contents)

2) [**Grandmothers and Granddaughters: Old-Age Pensions and Intrahousehold Allocation in South Africa**](https://www.jstor.org/stable/3990043?seq=1#page_scan_tab_contents)

3) [**Choices, Values, and Frames**](https://www.worldscientific.com/doi/abs/10.1142/9789814417358_0016)

## **2) Demand Theory**

The second class is devoted to demand theory.

### **Demand Theory**

#### [**Demand Theory**](https://en.wikipedia.org/wiki/Supply_and_demand): 

Let **X** $\in$ $\mathbb{R}^{L+}$ be the set of possible consumption vectors in a world with L goods. Let **p** $\in$ $\mathbb{R}^{L++}$ be the price vector. We want $B_{p,w}$ for the **budget set** of a consumer with wealth w. 

$B_{p,w}$ = {x $\in$ $\mathbb{R}^{L+}$ | $\sum_{i=1}^n$$p_ix_i$ ≤ w}. 

The [**utility maximization problem(UMP)**](https://en.wikipedia.org/wiki/Utility_maximization_problem) can be written as:

$max_{x\in B_{p,w}}$ u(x) or max$_{x\in \mathbb{R^{L+}}}$u(x) such that p $\circ$ x ≤ w.

Comments:

1) (smallness) consumption decisions do not affect prices.

2) linear prices typically justified (loosely) by possibility of resale.

3) no savings.

#### [**Marshallian Demand/Walrasian Demand Correspondence**](https://en.wikipedia.org/wiki/Marshallian_demand_function): 

Specifies what the consumer would buy in each price and income or wealth situation, assuming it perfectly solves the utility maximization problem. Formally: x(p,w): $\mathbb{R}^{L+}$ x $\mathbb{R}$ $	\rightrightarrows$ $\mathbb{R}^{L+}$ is defined by: x(p,w) = {z $\in$ $B_{p,w}$|u(z) = $max_{x \in B_{p,w}}u(x)$}.

#### **Propositions:**

Suppose u is continuous and satisfies local nonsatiation. Then:

1) The UMP problem has at least one solution.

2) x(p,w) is homogenous of degree 0, i.e. x($\alpha$p, $\alpha$w) = x(p,w) for all $\alpha$ > 0.

3) x(p,w) satisfies [**Walras’s law**](https://en.wikipedia.org/wiki/Walras%27s_law), i.e. p $\circ$ z = w for all z $\in$ x(p,w).

4) If u is strictly quasi-concave, then x(p,w) is a function, i.e.
each x(p,w) contains a single bundle.

#### [**Kuhn-Tucker**](https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions) necessary conditions






## **Useful** 

Prof: [**Parag Pathak**](https://economics.mit.edu/faculty/ppathak)

[**Syllabus 2018**](https://gabrielvoelcker.netlify.com/mit/syllabus_fall2018.pdf)

Required readings:

- [**Microeconomic Theory - Colell & Whinston**](https://gabrielvoelcker.netlify.com/mit/Mas-Colell,%20Whinston%20&%20Green%20-%20Microeconomic%20Theory.pdf)

- [**Microeconomic Foundations I - Kreps**](https://gabrielvoelcker.netlify.com/mit/David%20M.%20Kreps-Microeconomic%20Foundations%20I_%20Choice%20and%20Competitive%20Markets-Princeton%20University%20Press%20(2013).pdf)
