---
output: html_document
---

# 14.123 - Microeconomic Theory III{.tabset}

## **Lectures**{.tabset}

### **L1** 

#### **Static Deterministic Choice and Revealed Preference**

**Summary**: first lecture reviews the basics such as what are choices, preferences, revealed preferences and utility representations. It introduces preference relations and how those can be mapped to a utility function, while talking about rationality and WARP. 



- **Completeness**$^{12}$: for every set of alternatives(menus) X: agents know whether they prefer *x* or *y*. 

- **Transitive**$^{12}$: given *x*, *y* and *z*, if $x \succeq y$ and $y \succeq z$, then $x \succeq z$.

- **Rational**$^{13}$ = *Complete* + *Transitive*.

- **Anti-symmetric**$^{12}$: if $x \succeq y$ and $y \succeq x$, then *x* = *y*. 

- $^{15}$Every complete transitive preference defines a choice correspondence: $c_{\succeq}$(A) = \{ x $\in$ A : x $\succeq$ y $\forall y \in A$ \}.

- **Choice correspondence**: a map c:M(X) $\rightarrow$ M(X) s.t. c(A) $\subseteq$ A. c(A) gives the alternatives chosen when presented with menu A.

- **WARP**: if A,B $\in M$ and *x,y* $\in$ A $\cap$ B, $x \in C(A)$ and $y \in C(B)$ $\implies x \in C(B)$. In words, this means: 

    - WARP: implies Sen's $\alpha$: if $x \in A \subseteq B$ and $x \in C(B)$ $\implies$ $x \in C(A)$. 
    
    - **Weakly revealed preferred**: $\succeq^\ast$. If x $\succeq^\ast$ y $\implies$ x was chosen for any menu that contains *y*. 
    
- **Transitive closure**: when you can add terms between the relation x $\succeq^\ast$ y $\implies$ x $\succeq^\ast$ z $\succeq^\ast$ y.

- **Congruent**: if x $\succeq^\ast$ y and y $\in$ C(A) then x $\in$ C(A). In words, if *x* is revealed preferred to *y* and *y* is in the choice of *A* then *x* will also be in that choice too.

- **Utility preference**: $\forall$ x,y $\in$ X, x $\succeq$ y $\iff$ u(x) $\geq$ u(y). 

- **Debreu's Theorem**: if X is a convex subset of $\mathbb{R}^n$, then $\succeq$ is complete, transitive and continuous $\iff$ it has a representation by a continuous utility function. Proof sketch on slides 29-30.

- **Continuous**: upper and lower contour sets $\{ y \in X: y \succeq x \}$ and $\{ y \in X: x \succeq y \}$ are closed. 

- **Ordinal Utility**: if *u* represents $\succeq$, it is also represented by v $\iff$ there is a strictly increasing function $f: \mathbb{R} \rightarrow \mathbb{R}$ s.t. v = f $\circ$ u. In this sense, utility is **ordinal**: only the ordering matters (size matters not).

- **Continuous Revealed Preference Theory**: X = $\mathbb{R}^n_+$ free disposal menus equal budget sets. The data satisfies GARP. 

- **Afriat's Theorem**: if D is finite then the data satisfies GARP $\iff$ it can be generated by a continuous, concave, strictly increasing utility function.

#### **Proofs**

- $^{17}$Theorem (Arrow 1959): if M contains all subsets of two or three elements, then the choice data $c$ satisfies WARP $\iff$ the revealed preference relation is complete and transitive, and under WARP the choices predicted by the revealed preference relation match the data. That is $c_{\succeq *}$ = c. Proof in MWG. Relates to PS1-Q1.

- Proof of utility representation: suppose $X$ is finite, then there is a utility function that represents $\succeq$ $\iff$ $\succeq$ is complete and transitive.

- Proof of Debreu 1954: slides 29-30.

### **L2**

Readings for L2: 

- Huber, Payne and Puto(1982).

- Huber, Payne and Puto(2014).

- Strzalecki 1.1-1.8; 5.1-5.2.

- MWG 6A-B.

#### **Testing Revealed Preference Theory I, Methodology**

**Summary**: how do we test the revealed preference theory? Counter-examples: decoy effect, attraction effect, compromise effect. Static decisions under risk: $\Delta (Z)$ lotteries $\rightarrow$ what is the expected utility of a lottery p $\in \Delta(Z)$? Independence axiom. Cardinal uniqueness ("unique up to affine transformations").  

- **Rationalizable**: If choice probabilities can be generated by some v$\in$(U) then it's rationalizable. This means that if (P,X) is rationalizable for any x $\in$ X if x $\in$ A and A $\subseteq$ A' then P$_A$(x) $\geq$ P$_{A'}$(x). In words, if we give a larger choice set then choice probability/market shares of the originally available items cannot increase.

- **Decoy Effect**: adding a "decoy" into a choice menu, a decoy that is dominated by one alternative but not by the other, can lead to violations of regularity and implies violations of WARP. For example, people might buy more US\$100 items when a US\$200 is added, instead of the US\$ 50 one. 

- **Bernoulli Utility**: any function $u: Z \rightarrow \mathbb{R}$. 

- **Expected utility representation**: if there is a Bernoulli utility function *u* such that $U(p) = \sum_{z \in Z}p(z)u(z)$ represents $\succeq$. 

- **Independence Axiom**: $\forall$ p,q,r, $\in \Delta$(Z) and $\alpha \in (0,]$ we have that $p \succeq q$ implies $\alpha p + (1 - \alpha) r \succ$ $\alpha q + (1 - \alpha) r$). Regardless of the weight you assign to r, the first option will always be preferred. 

- **Consequentialism**: when nature rules out *r*, agent makes the same choice between *p* and *q*.

- **Dynamic consistency**: the agent makes same decisions in the 2 choice problems.

- **Dirac measure**: lotteries $\delta_z$ that surely gives *z* with probability 1.

- **Cardinal Uniqueness**: given 2 Bernoulli utility functions: *u* and *u'*, there is $a > 0$ and $b$ such that $\forall z \in Z$, u(z) = au'(z) + b and all such a,b give equivalent representations(unique up to affine transformations). Adding a constant or multiplying by some factor (as long as $a > 0$) to the utility of all outcomes won't change the ranking itself.

- **Jensen's Inequality**: an expected utility preference is risk averse/risk neutral/risk loving if *u* is concave/affine/convex.

- **CARA**(coefficient of absolute risk aversion): A(z) = $\frac{-u''(z)}{u'(z)}$.

#### **Proofs**:

- **von-Neumann Preferences**: preference $\succeq$ on $\Delta(Z)$ has an expected utility representation $\iff$ it's complete, transitive, continuous and has the independence axiom.

- **Cardinal uniqueness**.

### **L3**

Readings for L3: 

- Strzalecki 5.1-5.2.

- MWG 6A-C, optional 6D.

- Rabin (2000).

#### **Lotteries with Monetary Payoffs**

**Summary:** given EU representation of preference $\succeq$ on $\Delta (Z)$; coefficient of absolute risk aversion. Certain Equivalents. CARA preferences. Differentiating between risky and safe assets. Demand for insurance makes sense? Risk aversion: what are the stakes? Stochastic Dominance. 

- **Coefficient of Relative Risk Version**: R(w) = $\frac{-wu''(w)}{u'(w)}$ = an agent with increasing relative risk aversion gets more averse to proportional risks as he gets wealthier.

- **Certain Equivalents**: solve U(w + CE(p)) = U(w + p) for CE(p), when all realizations of *x* under lottery *p* are near Ep = $\mu$. Intuition: what's the least you'd accept with 100\% certainty instead of taking 1/2 chance of winning 10000 and 1/2 of winning 0.

- **Insurance against a purely monetary loss**. Optimal purchase of actuarially fair insurance only *equates the marginal utility* in the various states.

- **Insurance with state dependent utility**.

- **Risk preferences of insurances in the lab**: Given the wealth of most lab subjects, they
should be almost risk neutral to lab gambles(given they are small stakes), but they’re not.

- **First Order Stochastic Dominance**: p ≥$^{FOSD}$ q, if $F_p(x) ≤ F_q(x)\forall x$. It doesn't necessarily let us compare the realization of lotteries but we could represent them with a perfectly correlated lotteries where one is always as large as the other. **Theorem**: p ≥$^{FOSD}$ q $\iff \int u(dp) ≥ \int u(dq)$ for every weakly increasing function u: $\mathbb{R} \rightarrow \mathbb{R}$. *Intuition*: *p* FOSD *q* when *p* puts weakly more mass on higher values of *x* than *q*. 

- **Second Order Stochastic Dominance**: what if we add concavity to the expected utility of lotteries? If the supports of *p* and *q* lie in [a,b]m we say *p* SOSD *q*, *p* $\succeq^{SOSD}$ *q* if $\int_a^c F_q(x)dx ≥ \int_a^c F_p(X) dx \forall c \in [a,b]$. **Theorem**: assuming $Ep$ = $Eq$, then $p \succeq^{SOSD} q \iff \forall$ nondecreasing concave $u$ on [a,b] $\int_b^a ud F_p ≥ \int_a^b udF_q$. Intuitively, this comes from a related result, where $p SOSDs q$ only if we can write $p$ and $q$ as the marginal distributions of random variables $z_p$ and $z_q$ with $z_q = z_p + \epsilon$ and E($\epsilon | z_p$) ≤ 0.

#### Proofs

- **FOSD**: p ≥$^{FOSD} q \iff \int u(dp) ≥ \int u(dq)$ for every weakly increasing function u: $\mathbb{R} \rightarrow \mathbb{R}$.

### **L4**

Readings for L4:

- Strzalecki 5.4, 5.6.1-5.6.4.

- Fehr-Duda and Epper(2012).

- Fehr-Duda, Bruhin et. al (2010).


#### **Non-EU Risk Preferences**

**Summary**: Non-EU Risk Preferences (Allais Paradox). When EU fails, what model should we use? Prospect Theory. Calibrating Prospect Theory.  

- **The Allais Paradox**: choice questions that violates expected utility.

    - A: $1 \delta_1$ vs B $0.1 \delta_5 + 0.89 \delta_1 + 0.01 \delta_0$. Although expected utility is higher for B, considerably lot of people choose A.
    
    - C: $0.11\delta_1 + 0.89 \delta_0$ vs D: $0.1 \delta_5 + 0.9 \delta_0$. Again although EU of C is higher, a lot choose D.
    
    - Reason: use the independence axiom - $0.11 \delta_1 + 0.89 \delta_1 \succ 0.1 \delta_5 + 0.89 \delta_1 + 0.01 \delta_0 \rightarrow \delta_1 \succ (10/11)\delta_5 + (1/11)\delta_0$. 
    
- **Prospect Theory**: Reference-dependent preferences for changes to current wealth (to ac- commodate ”loss aversion.”). Preference over lotteries non-linear in probabilities via proba- bility weighting function. One critical problem is that the prospect theory allows violations of FOSD. This leads to rank-dependent expected utility and cumulative prospect theory.

- **Cumulative Prospect Theory**: under EU, one way to compute the expected utility is using "vertical stripes" as in Riemann integrals; another is using horizontal stripes using Lebesgue integration. CPT is like integrating the horizontal stripes, replacing *p* with $\pi(p)$ and this gives preferences tht follow FOSD. CPT has been used to explain a wide range of lab data, including why some people both buy insurance and lottery tickets. 


### **L5**

Readings:

- Bernheim and Sprenger (2019).

- Strzalecki 7.1-7.6.

- MWG 6F.

#### **Subjective Probability and Subjected Expected Utility**

**Summary**: EU has failures. Choice under **risk**. Choice under **uncertainty**. **Subjective** EU(Aumann). Mixture continuity. Monotonicity/Non-triviality/Independence. 

- **Subjective expected utility**: EU but where the probabilities *p* represent subjective belief. Famous: Savage(in Strzalecki's notes) and Anscombe-Aumann. We want to characterize when a complete transitive preference on $\mathcal{F}$(all acts) has a subjective expected utility representation of the form:

\[ V(f) = \sum_{s \in S} u(f(s))p(s)\]

Understand the extent to which *u*(utility) and *p*(subjective probability distribution) are pinned down. It's important that the utility function **doesn't depend on the state**.

- **Mixture continuity**: $\forall f,g,h \in \mathcal{F}$, the sets: 

\[ \{ \alpha \in [0,1]: \alpha f + (1 - \alpha)g \succeq h \} \]

and

\[ \{ \alpha \in [0,1]: \alpha f + (1 - \alpha)g \preceq h \} \]

are closed in [0,1].

- **Constant acts**: for z $\in$ Z or p $\in \Delta (Z)$, let $\overrightarrow{\rm z}$ and $\overrightarrow{\rm p}$ denote the **constant acts** that give $\delta_z$ or *p* in every state. 


- **Axiom: Monotonicity**: if $\overrightarrow{\rm f(s)} \succeq \overrightarrow{\rm g(s)} \forall s$, then f $\succeq$ g. Implicitly assumes it is state-independent(slide 17, L5).

- **Axiom: Non-triviality**: $\exists$ *f*, *g* $\in \mathcal{F}$ such that $f \succ g$.

- **Axiom: Independence**: $\forall f,g,h \in \mathcal{F}$ and $\alpha \in (0,1)$:

\[ f \succeq g \iff \alpha f + (1 - \alpha)h \succeq \alpha g + (1 - \alpha) h \]

Similar to independence but this is on a larger space.

- **Anscombe and Aumann 1952 Theorem**: a complete transitive preference $\succeq$ on $\mathcal{F}$ satisfies mixture continuity, monotonicity, non-triviality and independence $\iff$ there is a non-constant linear u: $\Delta (Z) \rightarrow \mathbb{R}$ and a *p* $\in \Delta(S)$ s.t. V(f) = $\sum_s u(f(s))p(s)$ represents $\succeq$. Moreover, p is unique and u is unique up to affine transformations. Intuition: calibrate subjective probabilities to objective ones. 

Suppose x,y $\in Z, \overrightarrow{\rm x} \succ \overrightarrow{\rm y}$.For each E $\in 2^S$, find the $\alpha$ s.t. $\alpha \overrightarrow{\rm x}$ + (1 - $\alpha$) $\overrightarrow{\rm y}$ $\sim$ $\overrightarrow{\rm x_Ey}$, where $\overrightarrow{\rm x_Ey}$ means the **act that pays x for s** $in E$ and **y for s** $\in S- E$. Upon finding it, it is our candidate for p(E). WTS that p(E) doesn't depend on the choice of x,y $\in Z$ and that *p* is a probability distribution. 

**Proof**: the goal is to characterize when a complete transitive preference on $\mathcal{F}$ has a subjective expected utility representation of the form V($f$) = $\sum_s u(f(s))p(s)$. And understand the extent to which *u* and *p* are pinned down. 

1) Th induced preference on $\Delta(Z)$ satisfies vN-M axioms $\rightarrow$ it is represented by a non-trivial utility function *u* that is linear in the objective probabilities. 

2) Normalize the range of *u* to be *U* = [-1,1]. Let's define a **utility act** in a way that in each state *s* get lottery with vN-M utility *u*: map $\tau$: S $\rightarrow$ U. Then the space of all utility acts is $U^S$. Define $\succeq^\ast$ on $U^S$ by $\tau \succeq^\ast \tau'$ $\iff$ $f \succeq g$ for some $f,g \in \mathcal{F}$ s.t. $\tau = u \circ f$ and $\tau' = u \circ g$.

3) **Claim**: from monotonicity we know that $\succeq^\ast$ doesn't depend on the choice of $f,g$ so it's a complete transitive preference. **Proof**: to show $\succeq^\ast$ doesn't depend on the choice of $f,g$: 
    
    a) Suppose $\exists f,f',g,g' \in \mathcal{F}$ s.t. $\tau = u \circ f = u \circ f'$ and $\tau' = u \circ g = u \circ g'$. 
    
    b) Then, $\forall s$, u(f(s)) = u(f'(s)), so f(s) $\sim$ f'(s), and from monotonicity: $\overrightarrow{\rm f(s)} \sim \overrightarrow{\rm f'(s)}$ for all s. So(using monotonicity again) f $\sim$ f'.
    
    c) Similarly g $\sim$ g'.
    
    d) Thus: f $\succeq$ g $\iff$ f' $\succeq$ g' $\iff$ $\tau \succeq^\ast \tau'$. 

4) Let I($\tau$) $\in$ [-1,1] for "indifference" be the **number s.t. the constant utility act** $\overrightarrow{\rm I(\tau)}$ **is indifferent to** $\tau$. I($\tau$) will end up being the expected utility of $\tau$ in our representation, but first we have to how I($\tau$) is well defined. **Claim**: I($\tau$) exists and is unique. Sketch:

    a) define upper and lower contour sets: $U(\tau) = \{ \eta \in [-1,1]: \overrightarrow{\rm \eta} \succeq \tau \}$ and L($\tau$) = \{ $\eta \in [-1,1] : \overrightarrow{\rm \eta} \preceq \tau \}$.
    
    b) These sets are non-empty, closed (from mixture continuity) and their union is [-1,1], so they have a non-empty intersection.
    
    c) From the definition of utility acts, this intersection is unique (otherwise $u > u'$ and (u,u,...,u) $\sim$ (u',u',...,u'))
    
    d) Define the intersection to be I($\tau$).
    
    e) note that by construction $\tau \succeq^\ast \sigma \iff I(\tau) \geq I(\sigma)$, so I represents $\succeq^\ast$. 

5) Use independence to show that $I(\lambda \tau)$ = $\lambda I(\tau)$. We do this in three steps:

    a) First we do this for $\lambda \in (0,1)$: 
    
      - Fix any $\tau \in U^S$, and any $f \in \mathcal{F}$ s.t. $\tau = u \circ f$.
      
      - Pick p,q $\in \Delta(Z)$ s.t. u(p) = I($\tau$) and u(q) = 0.
      
      - Then $f \sim \overrightarrow{\rm p}$, so by independence: $\lambda f + (1 - \lambda) \overrightarrow{\rm q} \sim \lambda \overrightarrow{\rm p} + (1 - \lambda) \overrightarrow{\rm q} = \overrightarrow{\rm (\lambda p + (1 - \lambda)q)}$

      - So $\lambda \tau \sim^\ast \overrightarrow{\rm \lambda I(\tau)}$ and thus $I(\lambda \tau)$ = I $\overrightarrow{\rm (\lambda I (\tau))} = \lambda I (\tau)$ (because I(u,u,...,u) = u).
      
    b) For $\lambda > 1$ and $\lambda \tau \in U^S$ start with $\lambda \tau$ and multiply by $\frac{1}{\lambda}$.
    
    c) Then extend $I$ to all of $\mathbb{R}^S$ by setting $I(\tau)$ = $||\tau||_1 I(\frac{\tau}{||\tau||_1})$. We took U = [-1,1] instead of U = [0,1] so we could do this. 
      
6) Similarly show *I* is additive, that is that:

\[ I(\lambda \tau + (1 - \lambda)\sigma) = \lambda I(\tau) + (1 - \lambda) I(\sigma) \]

7) Given *I* is a linear operator on $\mathbb{R}^S$ $\implies$ there is a unique vector *p* s.t. I($\tau$) = $\sum_s p(s) \tau(s)$.

8) This *p* is a probability distribution, i.e., each entry non-negative and sums to 1.

9) Set V(f) - $\sum_s u(f(s))p(s)$.

- **Eliciting Subjective Beliefs**: rather win \$ 10 for sure if Event *E* happnes or with probability *p* = (0.1, 0.2, ..., 1). Pick a probability *q* at random and give her the choice she selected. 

- **Confidence intervals exercise**.

### **L6**

Readings for L6:

- Strzalecki 7.5, 10.3-5.

- Halevy (2007).

Optional papers:

- Alpert and Raiffa (1982).

- Biais et al. (2005).

- Berner and Graber (2008).

- Camerer and Weber (1992).

- Trautmann and Van De Kuilen (2015).

### **L7**

Readings for L7:

- Strzalecki 2.

- Kreps (1979).

### **L8**

Readings:

- Strzalecki 3.1-3.3, 4.

## **Strzalecki Notes**

Not a summary, just interesting insights.

### **L2**

1.1-1.8; 5.1-5.2

#### **1.1 What is decision theory about?**

The consistency conditions that characterize utility maximization are expressed in terms of axioms on observed behavior. Axiomatization breaks the model into a collection of distinct properties. Each axiom can be discussed from two different perspectives: i) *positive*: people behave this way; ii) *normative*: people should behave this way.

#### **5.1. **

**Dirac Measure Definition**: $\forall z \in Z$, the Dirac measure on z attaches probability 1 to z. It is denoted $\delta_z \in \Delta(Z)$ and defined by $\delta_z(z) = 1$. The set $\Delta(Z)$ is convex with Dirac measures as extreme points and the following mixture operation.

**Definition 5.2 - Probability Mixture**: for any two probability distributions $p,q \in \Delta(Z)$ and a number $\alpha \in [0,1]$ we define a third probability distribution $\alpha p + (1 - \alpha)q \in \Delta(Z)$ which assigns probability $\alpha p (z) + (1 - \alpha)q(z)$ to each $z \in Z$.

Example: the probability measure that attaches probability $\alpha$ to $x$ and 1 - $\alpha$ to *y* can be written as $\alpha \delta_x + (1 - \alpha)\delta_y$. It is now clear that EU is linear in probabilities. 



### **L3**

5.4, 5.6.1-5.6.4

### **L4**

7.1, 7.6

#### **7.1 Uncertainty**

In reality, objective probabilities may not exist.

- **Subjective Expected Utility**: a preference $\succeq$ has a SEU representation if $\exists$ a probability measure P on S and a Bernoulli utility function u: Z $\rightarrow \mathbb{R}$ such that $\succeq$ is represented by:

\[ V(f) = \int_S u(f(s))  dP(s) \]

We assume that utility is **state-independent**.

#### **7.6 Anscombe-Aumman**

Allow a little "objective" probabilities:

Given finite state space S and a finite set of outcomes Z and consider $\mathcal{F} = (\Delta Z)^2$, with preferences $\succeq$ on $\mathcal{F}$. An act f: $S \rightarrow \Delta(Z)$ in each state *s* gives you an objective lottery $f(s)$. The idea is: we have an objective randomizing device(flip of a coin) but also states S $\leftarrow$ which are one-off contingencies where reasonable people can disagree.

First the state will be realized, then the randomizing will take place.


### **L5**




### **L6**

#### **Chapter 2**

Now we're concerned with a sequence of choices. We model these **temporally linked decisions** (decision trees).

Consider a 2-period model. Let $Z_0 = Z_1 = \mathbb{R}_+$ represent money. Endowment: $w_0 > 0$ dollars. By spending $c_0$ at t=0, you have less available dollars on t=1 when you choose from a menu which is the interval $A_1 (c_0)$ := [0,(1 + r)($w_0 - c_0$)], where $r$ is the interest rate. The menu at t=0 is: $A_0$ := \{$(c_0,A_1(c_0)) : c_0 \in [0, w_0]$ \}. 

The set of **all possible choices** at the two periods are: **1)** at **t=0** is $X_0$ := $Z_0 \times M(Z_1)$; **2)** at **t=1** is $X_1$ := $Z_1$. Members of $M(X_0)$ are called **decision trees**. 

In t=0, the analyst observes a **choice correspondence** $c_0$ : $M(X_0) \rightarrow M(X_0)$. Given that choices at t=1 can depend of what happened on t=0, we let $\mathcal{H}_0$ denote the set of all possible histories: 

\[ \mathcal{H}_0 := \{ (A_0,x_0) \in M(X_0) \times X_0 : x_0 \in c_0(A_0) \} \]

For each menu $A_1 \in M(X_1)$ in t=1, we define the set of histories that lead to that menu:

\[ \mathcal{H}_0 (A_1) := \{ (A_0, x_0) \in \mathcal{H}_0 : x_0 = (z_0,A_1) for some z_0 \in Z_0 \]

So the choice correspondence in t=1 will be history-dependent: choice from $A_1$ may depend on how we got to $A_1$. We then write $c_1 (A_1; A_0, x_0)$ to denote the choice from menu $A_1$ after history ($A_0, x_0$) happened at t=0. We define the domain of $c_1$ as:

\[ \mathcal{D}_1 := \{ (A_1; A_0, x_0) \in M(X_1) \times \mathcal{H}_0 : (A_0, x_0) \in \mathcal{H}_0(A_1)\} \]

Now we can define the choice correspondence:

**Definition 2.2 (Dynamic Choice Correspondence):** a pair $(c_0, c_1)$ is a *dynamic choice correspondence* whenever the choice correspondence at t=0, $c_0: M(X_0) \rightarrow M(X_0)$, is such that $c_0 (A_0) \subseteq A_0 \forall A_0 \in M(X_0)$ and choice corresponde at t=1, $c_1: \mathcal{D}_1 \rightarrow M(X_1)$, is such that $c_1 (A_1; A_0, x_0) \subseteq A_1 \forall (A_1;A_0,x_0) \in \mathcal{D}_1$. 

Two things can impact period 1's choice: 1) the menu $A_0$; 2) the item $x_0 = (z_0, A_1)$ chosen from $A_1$, or the payoff $z_0$ received.

##### **Assumptions of DCC:**

- **Consequentialism**: when we are choosing between options, we *should* only be looking at their consequences. Looking forward, the past should be irrelevant. Intuitive counter-example: what you had for lunch impacts your choice for dinner. A dynamic choice correspondence ($c_0,c_1$) satisfies *consequentialism* $\iff$

\[ c_1(A_1;A_0,c_0) = c_1(A_1;B_0,x_0) \]

for all $A_1 \in M(X_1)$ and all ($A_0,x_0$), ($B_0,x_0$) $\in \mathcal{H}_0 (A_1)$. Later, notation is simplified and write $c_1(A_1;z_0)$ $\leftarrow$ this object is well defined because for any ($z_0$,$A_1$) the choice period from $A_1$ is just $c_1(A-1;A_0,x_0)$ for some ($A_0,x_0$) $\in$ $\mathcal{H}_0 (A_1)$ such that $x_0 = (z_0, A_1)$; the particular choice of $A_0$ does not matter. Intuition: the choice from menu at t=0 is represented at whatever we're choosing in t=1 given we assumed consequentialism. 

- **Payoff-History Independence**: models often also assume consequentialism + Payoff-History Independence. That is: the choice in period 1 is independent of the payoff in period 0. It makes the model more tractable, however there are a few exceptions(ex: habit formation). A dynamic choice correspondence ($c_0; c_1$) satisfes payoff-history independence if and only if:

\[ c_1(A_1;z_0) = c_1(A_1;z_0') \]

for all $A_1 \in M(X_1)$ and all $z_0, z_0' \in Z_0$.

- **No Intermediate Payoffs**: we will abstract from intermediate payoffs, i.e. assuming that $Z_0 = \{z_0 \}$ for some fixed outcome $z_0$, but we will omit $z_0$ to simplify notation; henceforth, $X_0$ becomes $M(Z_1)$. 

- **WARP**: both $c_0,c_1$ satisfy WARP. 




















