---
output: html_document
---

# 14.382 - Applied Econometrics{.tabset}

## **Review** {.tabset}

### **L1**

#### **Gauss-Markov Properties of OLS**

**Summary**: review basic concepts of OLS. 4 Gauss-Markov assumptions needed for the OLS estimator to have good properties(GMA-GMD) $\rightarrow$ OLS is a good estimator and how to do inference. What can we state when GMA-GMD are satisfied.

### **L2**

#### **Asymptotic Theory for OLS**

**Summary**: 2 key conditions for asymptotic inference: asymptotic normality with asymptotic variance; $\hat{V}$ is a consistent estimator of the asymptotic variance V. Asymptotic t-ratios and confidence intervals. Nonsigularity of Q. Variance estimator $\hat{V}$. Heteroskedasticity robust variance estimator.  

### **L3**

#### **Heteroskedasticity**

**Summary**: individual heterogeneity: $y_i = X_i' \beta_i$. When do we have heteroskedasticity. Estimators of variance. Degrees of freedom correction. Unbiased under homoskedasticity. Jackknife Variance Estimator. 

### **L4**

#### **Cluster Consistent Estimation**

**Summary**: consider the estimation of the variance matrix for the OLS estimator when there is heteroskedasticity and when observations are correlated within groups of observations(clusters). What is clustering. Model and variance estimator with clusters. Asymptotic theory in clusters. 

### **L5**

#### **Bootstrapping for OLS**

**Summary**: instead of doing asymptotic approximation we estimate the distribution of objects(estimators, t-ratios). We estimate the distribution of any estimator by: 1) estimating the cumulative distribution function($F_0(z)$) by some $\hat{F}(z)$; 2) estimating the distribution of the estimator by what that distribution would be if $Z_i$ were i.i.d. with CDF $\hat{F}(z)$. 

Mid-page 2: sum of the steps of bootstrap estimator.

**Bootstrap Inference for an Estimator**: it ispossible to use the quantiles of the bootstrap distribution to form confidence intervals based on $\hat{\theta}$.


### **L6**

#### **Heteroskedasticity and Autocorrelation Consistent Variance Estimation**

**Summary**: how to estimate V$(\hat{\beta})$ when $\sum$ exhibits **autocorrelation** and heteroskedasticity(GMC is violated). Correcting the biased estimator. 









## **Lectures**{.tabset}

### **L1**

#### **Least Squares, Adaptive Partialling-Out, Simultaneous Inference**

Overview the least squares from several interesting angles. We discuss
Frisch-Waugh-Lovell **partialling out** and point out its **adaptivity property** in establishing approximate normality of the regression estimators of a set of target regression coefficients. We then discuss construction of simultaneous confidences sets for this set. We make use of the methods to analyze the gender wage gap and the impact of reemployment incentives on the duration of unemployment.

### **L2**

#### **Structural Equations Models and IV**

We study a very important linear structural model, with a **single endogenous variable** and a **single instrument**, which is frequently used in empirical analysis in economics. We show that we can identify, estimate, and perform **inference on the structural parameters** of the model using the **indirect least squares** method. We also provide inferential methods that are robust to weak instruments. The theory relies only upon conventional results for the least squares method. We apply the tools to revisit the analysis of returns-to-schooling and the impact of quality of institutions on economic growth. In the latter case, the use of inference methods robust to weak identification leads to a sharper lower bound on the impact of institutions quality than the original empirical results.

**Notation**: when two random vectors V and W obey: $EVW' = 0$ and W includes a constant, this means that *V* and *W* are **not correlated** in the sample. 

**Structural Equations Models**: specify a collection of **functional relations** between random variables, motivated by economic reasoning, plus unobserved **shock terms that obey certain orthogonality conditions**. The functional relations typically have causal interpretation. This is sometimes called **Simultaneous Equations Models**, here is a famous example: 

\[ Y = \alpha_1 D + \alpha_2' W + U \text{, } U \perp (W',Z')'\]

\[ D = \beta_1 Z + \beta_2' W + V \text{, } V \perp (W',Z')'\]

Again, W includes a constant.

The goal here is to learn the parameter $\alpha_1$, the return-to-schooling parameter, i.e., how education influences wages. The outcomes above are generated in two steps of a Nature's game:

1) random variables *W,Z,V,U* are generated subject to the orthogonality conditions specified above. 

2) Rvs *Y* and *D* are jointly determined by the system.

We call *W,Z* the predetermined or *exogenous variables*, and *Y,D* as jointly determined or *endogenous variables*. The unobserved variables *U,V* are called stochastic shocks or *error terms*. **Z** is the **instrumental variable** or excluded exogenous variable. 













