---
output: html_document
---

## Databases

The purpose of this file is to list relevant databases for researchers interested in accounting-related data.

### [**WRDS**](https://libguides.mit.edu/business/wrds)

- [**Compustat North America**](https://wrds-web-wharton-upenn-edu.libproxy.mit.edu/wrds/query_forms/navigation.cfm?navId=83): Use to find detailed fundamental data for companies trading on all of the major United States and Canadian exchanges. Coverage goes back to 1950.

- [**Compustat Global**](https://wrds-web-wharton-upenn-edu.libproxy.mit.edu/wrds/query_forms/navigation.cfm?navId=73): Compustat Global provides detailed fundamental data for major companies trading on international exchanges. Special files are available that contain financial services data, currency translations, and market data. Annual data date back to 1987 .

- Census Bureau Longitudinal Business Database... 

- Census Block Groups...

- Dealscan - Loan Pricing Corporation. contains information on loans obtained by firms and provides details of both price and non-price terms. 

- Securities Data Corporation (SDC) - Data on public bonds.