---
output: html_document
---

## **Day to Day** {.tabset}

[**MIT PhD Accounting**](https://gabrielvoelcker.netlify.com/mit/mitaccphd)

#### Today

#### Dec 17th

- Asset Pricing Exam: 9am - 12pm - E62-350.

- Microeconomics 2 Exam: 1:30 pm - 4:30 pm: E51-145.

- Start looking at Project.

#### Dec 16th

- Applied Econometrics Exam: 9 am - 12 pm: 50-340.

- Review for AP and Micro Exams.

#### Dec 15th

- Review for Metrics.


#### Dec 14th

- Redo 1 Micro Exam.

- Go over Metrics exercises.

#### Dec 13th

- Redo 1 Micro Exam.

- Go over Metrics exercises.

#### Dec 12th

- Redo 1 Micro Exam.   ✅

- Go over Metrics exercises.  ✅

- Look over next semester's courses.     🔘 

#### Dec 11th

- Redo 1 Micro Exam.   🔘 

- Read Leonid's notes.  ✅

- Go through AP PSets.   🔘 

#### Dec 10th

- Redo Metrics PSets.  🔘 

- Read Leonid's notes.   ✅

#### Dec 9th

- Redo Metrics PSets.  🔘 

- Read Leonid's notes.  ✅

#### Dec 8th

- Prepare to midterms. ✅

- Finish micro PS4. ✅

- MHE into RMarkdown. ✅

- Read Leonid's notes.  ✅

#### Dec 7th

- Prepare to midterms.   ✅

- Redo all micro Psets.   ✅

- Copy MHE to Rmarkdown.  🔘 

#### Dec 6th

- Present Rodrigo's paper.  ✅

- Get travel signature.  ✅

- Prepare to midterms. 🔘 

#### Dec 5th

- Rehearse Rodrigo's presentation.  ✅

- Prepare to midterms. 

- Hand in Metrics PS3. ✅

- Search for replication paper.  ✅

#### Dec 4th

- Finish Micro PSet.  ✅

- Prepare to midterms. 

- Prepare Rodrigo's presentation. ✅

#### Dec 3rd

- Prepare to midterms.  ✅

- Finish Micro PSet.  🔘 

- Read Asset Pricing.  ✅

- Acct trends.  ✅

#### Dec 2nd

- Finish Micro PSet. 🔘

- Read Asset Pricing.  ✅

- Prepare to Angrist. 

- Find replication paper. 🔘

- Read Rodrigo's papers.  ✅

#### Thanksgiving

- Find winter replication paper.

- Finish Rodrigo's presentation.

#### Nov 28th

- Micro PS 4. 🔘

- Read Rodrigo's paper. ✅

- Acct Trends.✅

#### Nov 27th

- Finish Metrics PS 3. ✅

- Acct Trends. 🔘

- Micro PS4.  🔘

#### Nov 26th

- Micro PSet 4. 🔘

- Read papers.

- Take a look at AP PSet 7.

- Acct trends. 🔘

#### Nov 25th

- Finish metrics PSet 2.   ✅

- Start Micro PSet 4.

- Acct Trends. 

#### Nov 23rd

- Finish Metrics PSet2.  🔘

- Rodrigo's paper.

- Acct trends.

#### Nov 22nd

- Metrics PSet2, all but Q3.  🔘

- Acct Trends.  ✅

- Start PPT paper Rodrigo.

#### Nov 21st

- Metrics PSet2, Q1, Q2, Q4.  🔘

- Read Aboody & Kasznik (2000).   🔘

- Acct Trends - collect Google Scholar data ex: for MIT.  ✅

#### Nov 20th

- Micro PSet 3.  ✅

- Asset Pricing PSet 6.  ✅

- Read Metrics. ✅

- Acct Trends.  🔘

#### Nov 19th

- Micro PSet 3.  ✅

- Asset Pricing PS step-by-step. 🔘  

- Read Metrics.

- Acct Trends.  🔘

#### Nov 18th

- Rodrigo's readings.  ✅

- Micro PSet 3.   🔘 

- Step by Step metrics set.   🔘 

#### Nov 17th

#### Nov 16th

- Finish Micro PSet 3.

- Step by step Asset Pricing PSet.

- Step by step Metrics PSet.
 
- Read Game Theory. ✅

#### Nov 15th

- Finish Micro PSet 3.  🔘 

- Step by step Asset Pricing PSet. 🔘 

- Inna's brown bag. ✅

- Acct Trends. ✅

#### Nov 14th

- Finish Micro PSet 3. 🔘 

- Plot with 3 info: volume, $\Delta$ price and trending/info indicator.
  
- Read metrics.🔘 

- Step by step Asset Pricing PSet.🔘 

- Trocar e destrocar de App store. ✅

#### Nov 13th

- Start Micro PSet 3. ✅

- Next paper: stock fluctuations. 

#### Nov 12th

- Micro2: organize semester.  ✅

- Map next psets.  ✅

- Read.

- Skype w/ Greg + Elvis.   ✅

- Next paper. ✅

#### Nov 11th

- Econometrics PS1. ✅

- Rodrigo's paper. ✅

- Prepare for Econometrics class.✅

#### Nov 10th:

- Econometrics PS1. 🔘 

#### Nov 9th

- JAE Conference. ✅

- Econometrics PS1: Exs: 1-2.

#### Nov/8th

- JAE Conference. ✅

- Econometrics PS1. 🔘 

#### Nov/7th.

- Start Econometrics PSet 1. ✅

- Questions from Econometrics class. ✅

- Start AP PSet 2. ✅

- Read Ross' notes. ⛔

- JAE Conference. ✅

- Python Finance at DataCamp. ⛔

#### Nov/6th.

- Cover all Angrist's Labor Economists Know The Score class. ✅

    - Specification testing? It's when the tester doesn't know how things are structured inside the black box. Initially thought as a possible approach to solve the problem posited at the beginning of the class.
    
    - Lalonde challenge?
    
    - Cell-specific treatment effect? 
    
    - Omitted Variables Bias Formula? The bias results in the model attributing the effect of the missing variables to the estimated effects of the included variables. The assumed specification is incorrect in that it omits an independent variable that is correlated with both the dependent variable and one or more of the included independent variables

- Cover all Propensity Score Matching from MHE. ✅

    - What is the difference/similarity between regression and matching?

    - Propensity Score Paradox?

- Skim Angrist's papers for tomorrow's class. ✅

- Read introductions of all 5 papers of JAE conference. ✅

    - Impairment and charge off.

- Python Finance at DataCamp.

- Learn how to access databases. ✅

### **To do's:**

#### Asset Pricing

- PSET 6: Nov 20th.

- Read Ross' notes.

- [**PS5**](https://www.overleaf.com/project/5dc1d3319fda550001327bd5) Asset Pricing. Understand and map steps.

  - Understand orthogonality on 3B.
  
  - [**Euler's Equation**](https://www.khanacademy.org/science/electrical-engineering/ee-circuit-analysis-topic/ee-ac-analysis/v/ee-eulers-formula): according to PS5 3B of asset pricing, we are supposed to dominate Euler's equation.

  - [**Intro to Portfolio Risk Management in Python**](https://campus.datacamp.com/courses/intro-to-portfolio-risk-management-in-python/factor-investing?ex=1). 

#### Econometrics

- Read Angrist's books.

#### Microeconomics II

- PSET 2: Nov 20th.

- Read Game Theory. 

#### Misc

- **Read JAE 2019 Conference Papers**.

- Install Stata.

- Install SAS.

- Understand databases.

### **Personal stuff:**

- Organize thanksgiving agenda. 

    - Call restaurant.
    
    - Sunday 24th: arrive. Campus visit + Isabella Stewart Gardner(w/ Max) + MFA(or on Wednesday).
    
    - Wednesday 27th:
    
    - Thursday 28th: NH + Ski + Thanksgiving Dinner.
    
    - Friday 29th: NH.
    
    - Saturday 30th: NH + Back to Boston + Hot Pot Dinner.
    
    - Sunday 1st: Lunch at Rodrigo. Dinner Moretti.
    
    - Monday 2nd: Lunch at Sloan. Dinner anywhere.
    
    - Tuesday 3rd: bye. 

- iPad?

### **Done**

- Buy winter coat. ✅

- Buy winter boots. ✅

- GoPro Max. ✅

- NBA tickets. ✅

- Mileage programs. ✅